TVShowsWatchlist/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from restapi import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tvshows/', include('tvshows.urls')),
    path('restapi/tvshows/', views.TvShowList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

tvshows/urls.py
from django.urls import path
from . import views

app_name = 'tvshows'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:tvShowId>', views.details, name='details'),
    path('serie/add', views.TvshowCreate.as_view(), name='tvshow-add'),
    path('<int:pk>/delete', views.TvshowDelete.as_view(), name='tvshow-delete'),
    path('<int:pk>/update', views.TvshowUpdate.as_view(), name='tvshow-update'),
    path('episodes/add', views.EpisodeCreate.as_view(), name='episode-add'),
    path('episodes/<int:pk>/update', views.EpisodeDelete.as_view(), name='episode-delete'),
    path('episodes/<int:pk>/delete', views.EpisodeUpdate.as_view(), name='episode-update'),
    path('seasons/add', views.SeasonCreate.as_view(), name='season-add'),
    path('seasons/<int:pk>/update', views.SeasonDelete.as_view(), name='season-delete'),
    path('seasons/<int:pk>/delete', views.SeasonUpdate.as_view(), name='season-update'),
]

restapi/models.py
from django.db import models

# Create your models here.

tvshows/models.py
from django.db import models
from django.urls import reverse

class TvShow(models.Model):
    title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    poster = models.CharField(max_length=1000)
    description = models.CharField(max_length=2500)
    productionCountry = models.CharField(max_length=40)

    def get_absolute_url(self):
        return reverse('tvshows:details', kwargs={'tvShowId': self.id})

    def __str__(self):
        return "[" + str(self.id) + "] " + self.title + " (" + self.productionCountry + ") - " + self.genre + "\n" + self.description[0:100] + "(...)"


class Season(models.Model):
    tvShow = models.ForeignKey(TvShow, on_delete=models.CASCADE)
    number = models.SmallIntegerField()

    def get_success_url(self):
        return reverse('tvshows:details', kwargs={'tvShowId': self.tvShow.id})

    def get_absolute_url(self):
        return reverse('tvshows:details', kwargs={'tvShowId': self.tvShow.id})

    def __str__(self):
        return self.tvShow.title + " - season " + str(self.number)


class Episode(models.Model):
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    number = models.SmallIntegerField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=2500)
    duration = models.DurationField()
    releaseDate = models.DateField()
    videoUrl = models.CharField(max_length=2500)

    def get_success_url(self):
        return reverse('tvshows:details', kwargs={'tvShowId': self.season.tvShow.id})

    def get_absolute_url(self):
        return reverse('tvshows:details', kwargs={'tvShowId': self.season.tvShow.id})

    def __str__(self):
        return self.season.tvShow.title + " [S" + str(self.season.number) + "E" + str(self.number) + "] [duration: " + str(self.duration) + "] released: " + str(self.releaseDate)

restapi/views.py
from django.shortcuts import render, get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from tvshows.models import TvShow, Season, Episode
from restapi.serializers import TvShowSerializer

class TvShowList(APIView):

    def get(self, request):
        tvShows = TvShow.objects.all()
        serializer = TvShowSerializer(tvShows, many=True)
        return Response(serializer.data)

tvshows/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from .models import TvShow, Episode, Season
from django.urls import reverse_lazy


def index(request):
    tvShowsList = TvShow.objects.all()
    context = {'tvShowsList': tvShowsList}

    return render(request, 'tvshows/index.html', context)


def details(request, tvShowId):
    tvShow = get_object_or_404(TvShow, id=tvShowId)
    context = {'tvShow': tvShow}

    return render(request, 'tvshows/details.html', context)


class TvshowCreate(CreateView):
    model = TvShow
    fields = ['title', 'genre', 'poster', 'description', 'productionCountry']


class TvshowUpdate(UpdateView):
    model = TvShow
    fields = ['title', 'genre', 'poster', 'description', 'productionCountry']


class TvshowDelete(DeleteView):
    model = TvShow
    success_url = reverse_lazy('tvshows:index')


class EpisodeCreate(CreateView):
    model = Episode
    fields = ['season', 'number', 'title', 'description', 'videoUrl', 'duration', 'releaseDate']

    def get_success_url(self):
        tvshow = self.object.season.tvShow
        return reverse_lazy('tvshows:details', kwargs={'tvShowId': tvshow.id})


class EpisodeUpdate(UpdateView):
    model = Episode
    fields = ['season', 'number', 'title', 'description', 'videoUrl', 'duration', 'releaseDate']

    def get_success_url(self):
        tvshow = self.object.season.tvShow
        return reverse_lazy('tvshows:details', kwargs={'tvShowId': tvshow.id})


class EpisodeDelete(DeleteView):
    model = Episode

    def get_success_url(self):
        tvshow = self.object.season.tvShow
        return reverse_lazy('tvshows:details', kwargs={'tvShowId': tvshow.id})

class SeasonCreate(CreateView):
    model = Season
    fields = ['tvShow', 'number']

    def get_success_url(self):
        tvshow = self.object.tvShow
        return reverse_lazy('tvshows:details', kwargs={'tvShowId': tvshow.id})


class SeasonUpdate(UpdateView):
    model = Season
    fields = ['number']

    def get_success_url(self):
        tvshow = self.object.tvShow
        return reverse_lazy('tvshows:details', kwargs={'tvShowId': tvshow.id})


class SeasonDelete(DeleteView):
    model = Season

    def get_success_url(self):
        tvshow = self.object.tvShow
        return reverse_lazy('tvshows:details', kwargs={'tvShowId': tvshow.id})

tvshows/templates/tvshows/base.html
<!doctype html>
<head>
    {% load static %}
    <meta charset="utf/8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>{% block siteTitle %} {% endblock %}</title>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Monoton' rel='stylesheet' type='text/css'>
    <script crossorigin="anonymous" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
            src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <link href="{% static 'tvshows/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'tvshows:index' %}">
                <img alt="" class="d-inline-block align-top" height="24" src="{% static 'tvshows/images/logo.png' %}"
                     width="30">
                TvShow Watchlist
            </a>
            <button aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler" data-bs-target="#navbarColor01" data-bs-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a aria-current="{% url 'tvshows:index' %}" class="nav-link active" href="{% url 'tvshows:index' %}">Explore</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tvshows:tvshow-add' %}">Add new show</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input aria-label="Search" class="form-control me-2" placeholder="search for tv show..."
                           type="search">
                    <button class="btn btn-outline-light" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>


<div class="container">
    <div class="row ">
        <main>
            <section id="mainTitleInfo" class="py-5 text-center container">
                <div class="row py-lg-2">
                    <div class="col-lg-6 col-md-8 mx-auto">
                        {% block mainSectionHeader %} {% endblock %}
                        <p class="lead text-muted">{% block mainSectionContent %} {% endblock %}</p>
                    </div>
                </div>
            </section>
        </main>
    </div>
    <div class="row d-flex justify-content-center">
            {% block content %} {% endblock %}
    </div>
</div>

<footer class="text-muted py-3 bg-dark footer">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#" style="nav-link">Back to top</a>
    </p>
    <p class="mb-1"><strong>Tv Show Watchlist ©</strong> Projekt na Systemy Zarządzania Treścią, Oliwia Jakobsce indeks 106545</p>
  </div>
</footer>
<script crossorigin="anonymous" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

tvshows/templates/tvshows/details.html
{% extends 'tvshows/base.html' %}

{% block title %} {{ tvShow.title }} - information{% endblock %}
{% block mainSectionHeader %} <h1> Details of <span id="tvShowTitleInDetails"> {{ tvShow.title }} </span> series
</h1> {% endblock %}
{% block mainSectionContent %} Find new amazing show to binge-watch today. {% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="row" style="padding-top: 1em">

        <!-- Tv show basic information -->
        <div id="tvShowInfoInDetails" class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><h1> {{ tvShow.title }} </h1></li>

                        <li class="list-group-item"><a href="{% url 'tvshows:details' tvShow.id %}">
                            {% if tvShow.poster %}
                            <img src="{{ tvShow.poster }}" class="img-responsive" style="width: 100%">
                            {% else %}
                            <h3>No image to display</h3>
                            {% endif %}
                        </a></li>

                        <li class="list-group-item"><strong>Production country:</strong> {{ tvShow.productionCountry }}
                        </li>
                        <li class="list-group-item"><strong>Genre:</strong><small>{{ tvShow.genre }}</small></li>
                        <li class="list-group-item"><strong>Description:</strong> {{ tvShow.description }}</li>
                    </ul>
                </div>
            </div>
        </div>


        <!-- Seasons and episodes -->
        <div class="col-sm-8 col-md-9">

            <!-- DELETE TV SHOW -->
            <form action="{% url 'tvshows:tvshow-delete' tvShow.id %}" method="post" style="display:inline; float: right; margin-left: 2px; margin-right: 2px">
                {% csrf_token %}
                <input type="hidden" name="tvshow_id" value="{{ tvShow.id }}"/>
                <button type="submit" class="btn btn-danger btn-sm">
                    Delete show
                </button>
            </form>

            <!-- UPDATE TV SHOW -->
            <form action="{% url 'tvshows:tvshow-update' tvShow.id %}" method="" style="display:inline; float: right; margin-left: 2px; margin-right: 2px">
                {% csrf_token %}
                <input type="hidden" name="tvshow_id" value="{{ tvShow.id }}"/>
                <button type="submit" class="btn btn-primary btn-sm">
                    Edit show
                </button>
            </form>

            <!-- ADD NEW EPISODE -->
            <a href="{% url 'tvshows:season-add' %}" class="btn btn-success btn-sm" style="float: right; margin-left: 2px; margin-right: 2px">Add new season</a>

            <!-- ADD NEW EPISODE -->
            <a href="{% url 'tvshows:episode-add' %}" class="btn btn-success btn-sm" style="float: right; margin-left: 2px; margin-right: 2px">Add new episode</a>

            <!-- Listing seasons and episodes -->
            <div class="panel panel-default extra-pad-top">
                <div class="panel-body">

                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    {% for season in tvShow.season_set.all %}
                    <h4 class="season-header" style="color: #d21212; font-weight: 600;">Season {{ season.number }}
                             <!-- EDIT EPISODE -->
                                 <form action="{% url 'tvshows:season-update' season.id %}" method="" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="season_id" value="{{ episode.id }}"/>
                                    <button type="submit" class="btn btn-link btn-sm">
                                        Edit
                                    </button>
                                </form>
                                <!-- DELETE EPISODE -->
                                <form action="{% url 'tvshows:season-delete' season.id %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="season_id" value="{{ episode.id }}"/>
                                    <button type="submit" class="btn btn-link btn-sm">
                                        Delete
                                    </button>
                                </form>
                    </h4>
                    {% if season.episode_set.all %}
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Episode nr</th>
                            <th class="w-50">Title</th>
                            <th>Duration</th>
                            <th>Released</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for episode in season.episode_set.all %}
                        <tr>
                            <td>{{ episode.number }}</td>
                            <td>
                                <div class="accordion accordion-flush" id="accordionFlushExample{{episode.id}}">
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="flush-headingOne{{episode.id}}">
                                            <button class="accordion-button collapsed" type="button"
                                                    data-bs-toggle="collapse"
                                                    data-bs-target="#flush-collapseOne{{episode.id}}"
                                                    aria-expanded="false"
                                                    aria-controls="flush-collapseOne{{episode.id}}">
                                                {{ episode.title }}
                                            </button>
                                        </h2>
                                        <div id="flush-collapseOne{{episode.id}}" class="accordion-collapse collapse"
                                             aria-labelledby="flush-headingOne{{episode.id}}"
                                             data-bs-parent="#accordionFlushExample{{episode.id}}">
                                            <div class="accordion-body"> {{ episode.description }}
                                                body.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>{{ episode.duration }}</td>
                            <td>{{ episode.releaseDate }}</td>
                            <td class="float: right">

                                    <a href="#" class="btn btn-primary btn-sm">Watch</a>
                                <!-- EDIT EPISODE -->
                                 <form action="{% url 'tvshows:episode-update' episode.id %}" method="" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="episode_id" value="{{ episode.id }}"/>
                                    <button type="submit" class="btn btn-dark btn-sm">
                                        Edit
                                    </button>
                                </form>
                                <!-- DELETE EPISODE -->
                                <form action="{% url 'tvshows:episode-delete' episode.id %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="episode_id" value="{{ episode.id }}"/>
                                    <button type="submit" class="btn btn-dark btn-sm">
                                        Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <p>No episodes added yet.</p>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

tvshows/templates/tvshows/episode_form.html
{% extends 'tvshows/base.html' %}

{% block title %} {{ tvShow.title }} - information{% endblock %}
{% block mainSectionHeader %} <h1> Add or edit an <span id="tvShowTitleInDetails"> episode </span> now
</h1> {% endblock %}
{% block mainSectionContent %}  {% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row d-flex justify-content-center" style="padding-top: 1em ">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% include 'tvshows/form-template.html' %}
                        <div>
                            <div class="mb3 d-flex justify-content-center w-100">
                                <button type="submit" class="btn btn-primary w-75">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

tvshows/templates/tvshows/form-template.html
{% for field in form %}
<div class="mb-3">
    {{ field.label_tag }}
    {{ field }}
    <span  class="text-danger" style="color: green">{{ field.errors }}</span>
</div>
{% endfor %}

tvshows/templates/tvshows/index.html
{% extends 'tvshows/base.html' %}

{% block title %} List of Tv shows {% endblock %}
{% block mainSectionHeader %} <h1 id="tvShowsTitle">List of Tv shows</h1> {% endblock %}
    {% block mainSectionContent %} Find new amazing show to watch today or check more to read about new episodes. {% endblock %}
{% block content %}
<br/>

<div class="row row-cols-1 row-cols-md-3 g-4">
    {% if tvShowsList %}
    {% for tvShow in tvShowsList %}
      <div class="col-sm-5 col-lg-3">
        <div class="card h-100">
          <img src="{{ tvShow.poster }}" class="card-img-top" alt="...">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">{{ tvShow.title }}</h5>
            <p>({{ tvShow.genre }}, {{ tvShow.productionCountry }})</p>
            <p class="card-text">{{ tvShow.description }}</p>
            <a href="{% url 'tvshows:details' tvShow.id %}" class="w-100 mt-auto btn btn-red btn-md" >Show more</a><br>
          </div>
        </div>
      </div>
    {% endfor %}
    {% else %}
    <p>Sorry, it seems that database is empty.</p>
{% endif %}
</div>

{% endblock %}

tvshows/templates/tvshows/season_form.html
{% extends 'tvshows/base.html' %}

{% block title %} {{ tvShow.title }} - information{% endblock %}
{% block mainSectionHeader %} <h1> Add or edit a <span id="tvShowTitleInDetails"> season </span> series
</h1> {% endblock %}
{% block mainSectionContent %}  {% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row d-flex justify-content-center" style="padding-top: 1em ">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% include 'tvshows/form-template.html' %}
                        <div>
                            <div class="mb3 d-flex justify-content-center w-100">
                                <button type="submit" class="btn btn-primary w-75">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

tvshows/templates/tvshows/tvshow_form.html
{% extends 'tvshows/base.html' %}

{% block title %} {{ tvShow.title }} - information{% endblock %}
{% block mainSectionHeader %} <h1> Add a new <span id="tvShowTitleInDetails"> tv show </span> series </h1> {% endblock %}
{% block mainSectionContent %}  {% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row d-flex justify-content-center" style="padding-top: 1em ">
        <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" >
                        {% csrf_token %}
                        {% include 'tvshows/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
             </div>
        </div>
    </div>
</div>

{% endblock %}